# This file is DISABLED - it interferes with the main docker-compose.yml
# DO NOT USE THIS FILE DIRECTLY
# Instead, run from the main cloud-u-l8r directory:
#   cd /home/tony/Documents/cloud-u-l8r
#   docker-compose up -d
#
# Or use the startup script:
#   bash /home/tony/Documents/cloud-u-l8r/start-stack.sh

version: '3'
services: {}
